services:
  pbs-client:
    build: .
    image: pbs-client-local:latest
    container_name: pbs-client
    restart: "no"


    env_file:
      - .env


    volumes:
    # Pastas locais para backup
    - /:/host:ro


    # Arquivo de configuração
    - ./backup.conf:/config/backup.conf:ro


    # Cache/keys
    - ./data:/data
    # entrypoint is baked into the image
    command: []